version: "3"

tasks:
  debug:
    desc: "Run development server with debugger"
    cmds:
      - DEBUG_ATTACH=nowait DEBUG_PORT=48016 uv run hypercorn celine.nudging.main:app --bind 0.0.0.0:8016

  test:
    desc: Run tests
    cmds:
      - uv run pytest -- {{.CLI_ARGS}}

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags

  alembic:migrate:
    desc: "Run migrations"
    cmds:
      - uv run alembic upgrade head

  alembic:sync-model:
    desc: "Generate a new alembic migration. Usage: task alembic:sync-model -- 'short description'"
    cmds:
      - uv run alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  alembic:reset:
    desc: "Reset DB schema"
    cmds:
      - uv run alembic downgrade base
