version: "3"

tasks:
  setup:
    cmds:
      - uv sync

  debug:
    desc: "Run development server with debugger"
    cmds:
      - LOG_LEVEL=DEBUG DEBUG_ATTACH=nowait DEBUG_PORT=48016 .venv/bin/uvicorn celine.nudging.main:create_app --reload --host 0.0.0.0 --port 8016

  test:
    desc: Run tests
    cmds:
      - uv run pytest -- {{.CLI_ARGS}}

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags

  alembic:migrate:
    desc: "Run migrations"
    cmds:
      - uv run alembic upgrade head

  alembic:sync-model:
    desc: "Generate a new alembic migration. Usage: task alembic:sync-model -- 'short description'"
    cmds:
      - uv run alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  alembic:reset:
    desc: "Reset DB schema"
    cmds:
      - uv run alembic downgrade base
