"""

Revision ID: 73a5308230a8
Revises: 8a2a854458f2
Create Date: 2026-02-23 10:12:27.551654

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a5308230a8'
down_revision: Union[str, None] = '8a2a854458f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nudges_log', sa.Column('community_id', sa.String(length=128), nullable=True))
    op.add_column('user_preferences', sa.Column('id', sa.String(length=64), nullable=False))
    op.add_column('user_preferences', sa.Column('community_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint('uq_user_pref_user_community', 'user_preferences', ['user_id', 'community_id'])
    op.add_column('web_push_subscriptions', sa.Column('community_id', sa.String(length=128), nullable=True))
    op.drop_constraint(op.f('uq_webpush_user_endpoint'), 'web_push_subscriptions', type_='unique')
    op.create_unique_constraint('uq_webpush_user_endpoint_community', 'web_push_subscriptions', ['user_id', 'endpoint', 'community_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_webpush_user_endpoint_community', 'web_push_subscriptions', type_='unique')
    op.create_unique_constraint(op.f('uq_webpush_user_endpoint'), 'web_push_subscriptions', ['user_id', 'endpoint'], postgresql_nulls_not_distinct=False)
    op.drop_column('web_push_subscriptions', 'community_id')
    op.drop_constraint('uq_user_pref_user_community', 'user_preferences', type_='unique')
    op.drop_column('user_preferences', 'community_id')
    op.drop_column('user_preferences', 'id')
    op.drop_column('nudges_log', 'community_id')
    # ### end Alembic commands ###
