preferences:
- user_id: user-it
  community_id: comm-1
  lang: it
  channel_web: true
  channel_email: false
  channel_telegram: false
  channel_whatsapp: false
  max_per_day: 5
  consents:
    notifications: true
- user_id: user-en
  community_id: comm-2
  lang: en
  channel_web: true
  channel_email: false
  channel_telegram: false
  channel_whatsapp: false
  max_per_day: 5
  consents:
    notifications: true
- user_id: user-es
  community_id: comm-3
  lang: es
  channel_web: true
  channel_email: false
  channel_telegram: false
  channel_whatsapp: false
  max_per_day: 5
  consents:
    notifications: true
- user_id: user-ca
  community_id: comm-3
  lang: ca
  channel_web: true
  channel_email: false
  channel_telegram: false
  channel_whatsapp: false
  max_per_day: 5
  consents:
    notifications: true
- user_id: user-default
  community_id: comm-1
  channel_web: true
  max_per_day: 5
  consents:
    notifications: true
- user_id: user-no-consent
  community_id: comm-1
  lang: it
  channel_web: true
  max_per_day: 5
  consents:
    notifications: false
